### ISSUE TITLE
The size of snap package is too big & can be optimized

### ISSUE THREAD

**Issue by keshavbhatt** [mirkobrombin/Amusiz#1]
Hi, I just inspected your snapcraft.yaml file (I suppose is being used to build snap package) and found there are lots of packages in stage package that are not required like i don't know why you need those lib-dev packages go inside the final snap? Also are you sure the gstreamer packages you adding to stage package do not already  exists in the gnome content snap that you using? I learned from the [docs]( https://docs.flatpak.org/en/latest/available-runtimes.html#gnome  ) that they package GStreamer, and even WebKitGTK inside the gnome runtime content snap. The snapcraft file need to be inspected to bring the size of your application down. If you need help, visit http://forum.snapcraft.io/ open a forum post, ask people for help etc.

**Comment by mirkobrombin** [comment]
The webkitgtk bundled in the gnome extension is too old. The gstreamer plugins are required for Amazon music to function properly, otherwise a message is displayed inviting you to use Chrome.

**Comment by keshavbhatt** [comment]
> Ps. you link the flatpak docs, this is the snapcraft one https://snapcraft.io/docs/gnome-3-38-extension

Yes, the docs here says they are derived from [gnome-platform-sdk](https://gitlab.gnome.org/Community/Ubuntu/gnome-sdk/blob/gnome-3-38-2004/snapcraft.yaml) . You can check what is already inside the content snap built with the recipe and avoid adding them in your snap stage-package, cause if you do there is no use of using content snap. The webkit version thing is reasonable though. 

Cheers, for the updates. You managed to reduce size of your final snap nearly by 42% :)

**Comment by mirkobrombin** [comment]
> > Ps. you link the flatpak docs, this is the snapcraft one https://snapcraft.io/docs/gnome-3-38-extension
> 
> Yes, the docs here says they are derived from [gnome-platform-sdk](https://gitlab.gnome.org/Community/Ubuntu/gnome-sdk/blob/gnome-3-38-2004/snapcraft.yaml) . You can check what is already inside the content snap built with the recipe and avoid adding them in your snap stage-package, cause if you do there is no use of using content snap. The webkit version thing is reasonable though. 
> 
> Cheers, for the updates. You managed to reduce size of your final snap nearly by 42% :)
> 
> 

Thanks for your contribution!

**Comment by keshavbhatt** [comment]
> Thanks for your contribution!
Man, Sorry i couldn't make it to a PR, been too busy maintaining my own apps lately. 
I also noticed some more issues :
- App launcher find no icon for your application, tested in Unity 7 Desktop. 
- The mainwindow is not draggable with mouse, tested in Unity 7 Desktop. 
I am using Unity 7 desktop for my work, so I was only able to test your app in Unity 7.

**Comment by mirkobrombin** [comment]
> > Thanks for your contribution!
> 
> Man, Sorry i couldn't make it to a PR, been too busy maintaining my own apps lately.
> I also noticed some more issues :
> 
> * App launcher find no icon for your application, tested in Unity 7 Desktop.
> * The mainwindow is not draggable with mouse, tested in Unity 7 Desktop.
>   I am using Unity 7 desktop for my work, so I was only able to test your app in Unity 7.

I'm working on it
