### ISSUE TITLE
black windows

### ISSUE THREAD

**Issue by gerhardbeck** [mirkobrombin/Amusiz#10]
Hi, I just started the App image (on Ubuntu 20.04) and just see a black window
![grafik](https://user-images.githubusercontent.com/41069802/137128257-8943c16e-8ad9-462b-843b-ca8cb84a1b3b.png)

**Comment by mirkobrombin** [comment]
Amusiz was temporary killed by DRM https://github.com/mirkobrombin/Amusiz/issues/8#issuecomment-879334509
