### ISSUE TITLE
Gdk-ERROR **: 19:29:45.176: The program 'WebKitWebProcess' received an X Window System error.

### ISSUE THREAD

**Issue by ZeroDot1** [mirkobrombin/Amusiz#11]
(WebKitWebProcess:3425316): Gdk-ERROR **: 19:29:45.176: The program 'WebKitWebProcess' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 211 error_code 2 request_code 152 (GLX) minor_code 34)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

![Bildschirmfoto vom 2022-11-02 19-30-58](https://user-images.githubusercontent.com/28985171/199572906-daf31448-02bc-47fd-b324-a54a7f8ed77e.png)

**Comment by mirkobrombin** [comment]
Hi, Amazon killed this application. Follow the discussion here: https://github.com/mirkobrombin/Amusiz/issues/8
