### ISSUE TITLE
Login information is lost between app launches

### ISSUE THREAD

**Issue by saveli** [mirkobrombin/Amusiz#2]
Between app launches only the username is remembered, the password is forgotten.

On a side-note: The first time you launch the app the language defaults to Italian. Maybe change it to English or let one choose.

**Comment by mirkobrombin** [comment]
Probably because the application starts with Amazon IT but you log into Amazon US (?) so at the next start you are again on Amazon IT but logged out.I'll get a fix as soon as possible, thanks for reporting

**Comment by saveli** [comment]
Another thing I just noticed, when I use the search bar on top I immediately have to login again, then the search is done.
It uses HTTP-percent-encoding, thereby the search result is often empty as the white space ' ' is replaced by '%20'

**Comment by mirkobrombin** [comment]
> Another thing I just noticed, when I use the search bar on top I immediately have to login again, then the search is done.
> It uses HTTP-percent-encoding, thereby the search result is often empty as the white space ' ' is replaced by '%20'

**Comment by saveli** [comment]
Interesting.. maybe its happening because of the intermediate relogin step?
This is happening for me:
![image](https://user-images.githubusercontent.com/18439300/118812238-6d6a6e80-b89d-11eb-91ae-e9f709b815e5.png)

**Comment by mirkobrombin** [comment]
This is actually weird. Can you try with the latest 1.0.1? The snap should be in the build on the way.

**Comment by saveli** [comment]
Hmm... latest available in snap is #848111e

**Comment by mirkobrombin** [comment]
Latest release is c21449f, it may take a few hours to deploy.

**Comment by saveli** [comment]
After reinstall, first login screen is now US instead of IT. But after that same errors as above.

**Comment by mirkobrombin** [comment]
> After reinstall, first login screen is now US instead of IT. But after that same errors as above.

By the "same problem as above" do you mean the search or the session?

**Comment by saveli** [comment]
Both. Login required between app launches, login required for each search.

**Comment by mirkobrombin** [comment]
> Both. Login required between app launches, login required for each search.

I tried in a new VM with Ubuntu 21.04 using snap and it works with every language. I also tried with Manjaro and Arch linux but the result is the same. Everything works, I believe it is a specific problem with your system.

**Comment by saveli** [comment]
In `~/.snap` theres no `amusiz` directory, only a `warning.json` with an entry caused by amusiz
```
2021-05-21T10:52:01+02:00 INFO snap "amusiz" has bad plugs or slots: dbus (cannot find attribute 'bus')
```
I found the `cookies.txt` in `~/snap/amusiz/12`, deleting that didn't change anything.

What actually helped was to change the language under preferences to the respecting Amazon login site where you created your account on. Meaning it is not a preference, but the "language" must match your account creation site. You can then change the display language using your profile in the webview after login. Thereby "language" under preferences is misleading, it should state something like "login site Amazon.{com, de, it, co.uk, ...}"

So now I don't have to retype the password each time, but from the animation and the showed amazon music logo, I see that I am still logged in anew for every search. This procedure takes ~3s and cancels current playback.

So per se this issue is resolved, but in a unsatisfying way :/

**Comment by mirkobrombin** [comment]
"Unsatisfying" due to the "wrong" string in the preferences?

Btw for the problem with the search open a new issue please.

**Comment by saveli** [comment]
> "Unsatisfying" due to the "wrong" string in the preferences?

It is unsatisfying because although I don't have to manually type the password the current "workflow" (browsing, adding to playlist, listening to current song, what else) is still interrupted.

> Btw for the problem with the search open a new issue please.

Will do.

**Comment by mirkobrombin** [comment]
> > "Unsatisfying" due to the "wrong" string in the preferences?
> 
> It is unsatisfying because although I don't have to manually type the password the current "workflow" (browsing, adding to playlist, listening to current song, what else) is still interrupted.
> 
> > Btw for the problem with the search open a new issue please.
> 
> Will do.

This shouldn't be the case, we're experiencing different workflows. I will wait for other reports.
