### ISSUE TITLE
cannot find attribute 'bus'

### ISSUE THREAD

**Issue by Tocinofrito** [mirkobrombin/Amusiz#7]
At the end of install the snap throw a warning:
snap "amusiz" has bad plugs or slots: dbus (cannot find the attribute 'bus')
![Screenshot from 2021-07-07 17-51-50](https://user-images.githubusercontent.com/40874235/124838254-10f60800-df4c-11eb-8a67-6d4ac2696fd4.png)

**Comment by mirkobrombin** [comment]
I think there are some test lines left in the snapcraft file, thanks for the tip
