### ISSUE TITLE
Doesn't show up in Snapcraft website and Snapcraft link doesn't work (obviously)

### ISSUE THREAD

**Issue by chookity-pokk** [mirkobrombin/Amusiz#9]
The Snapcraft Icon in your readme leads to an error not found so I thought about making a pull request and fixing that but I couldn't find it on snapcraft either. Also, when trying to install via snap it says "Amusiz" is an invalid name.

**Comment by mirkobrombin** [comment]
Please read #8

**Comment by chookity-pokk** [comment]
Ah, well shit. Best of luck with a new version.

**Comment by mirkobrombin** [comment]
> Ah, well shit. Best of luck with a new version.

Thanks, I need a lot of luck: D
